# **EKSTRAK LONGITUDE DAN LATITUDE MENGGUNAKAN HERE API**

In [ ]:
import requests
import pandas as pd
import time

In [ ]:
API_KEY = "ZlxPC6jHOSFfkREkwdKY8S1NLV61Su8niqKB0Dp259w"
BASE_URL = "https://geocode.search.hereapi.com/v1/geocode"

In [ ]:
INPUT_FILE = "Daftar SPPG.xlsx"
OUTPUT_FILE = "output_geocode.xlsx"

In [ ]:
df = pd.read_excel(INPUT_FILE)

In [ ]:
def geocode_address(address: str):
    if not isinstance(address, str) or not address.strip():
        return None, None

    params = {
        "q": address,
        "apiKey": API_KEY,
        "in": "countryCode:IDN"
    }

    try:
        response = requests.get(BASE_URL, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()
        items = data.get("items", [])
        if not items:
            return None, None

        pos = items[0].get("position", {})
        lat = pos.get("lat")
        lng = pos.get("lng")

        # tambahan verifikasi wilayah Indonesia
        if lat is None or lng is None:
            return None, None
        if not (-11 < lat < 7 and 95 < lng < 141):
            return None, None

        return lat, lng

    except Exception as e:
        print(f"Error untuk alamat '{address}': {e}")
        return None, None

In [ ]:
latitudes = []
longitudes = []

for idx, row in df.iterrows():
    SPPG = row.get("NamaSPPG", "")
    alamat = row.get("Alamat", "")
    alamat_baru = f"{SPPG}, {alamat}"
    print(f"[{idx}] Geocode: {alamat_baru}")

    lat, lng = geocode_address(alamat_baru)
    latitudes.append(lat)
    longitudes.append(lng)

    time.sleep(0.2)

Streaming output truncated to the last 5000 lines.
[5030] Geocode: SPPG Pati Kayen Kayen 2, Dusun Karanggempol, Rt.05 Rw. 8, Kayen, Kec. Kayen, Kabupaten Pati, Provinsi Jawa Tengah
[5031] Geocode: SPPG Pekalongan Buaran Coprayan 2, Coprayan Rt 07 Rw 03 Kec. Buaran Kab. Pekalongan, Jawa Tengah
[5032] Geocode: SPPG Kebumen Kebumen Wonosari, Jalan Kutoarjo Km 4,5 Desa Wonosari RT 01 RW 02, Kecamatan Kebumen, Kabupaten Kebumen, Jawa Tengah
[5033] Geocode: SPPG Sukoharjo Polokarto Wonorejo, Dukuh Jengglong Rt 3 Rw 5, Ds. Jatisobo, Kec. Polokarto, Kab. Sukoharjo, Jawa Tengah
[5034] Geocode: SPPG Sukoharjo Tawangsari Kateguhan, Jl. Raya Dalangan, Karangasem, Kateguhan, Kec. Tawangsari, Kab. Sukoharjo, Jawa Tengah
[5035] Geocode: SPPG Sragen Sumberlawang Mojopuro, Jalan Solo-Purwodadi, Kebayanan II, Mojopuro, kecamatan Sumberlawang, Kabupaten Sragen, Jawa Tengah
[5036] Geocode: SPPG Kebumen Kebumen Karangsari, Dukuh Ampel Rt 04 Rw 04, Karangsari, Kebumen, Kab. Kebumen, Jawa Tengah
[5037] Geocode: SPPG Banjarnegara Punggelan Petuguran, Dusun Petuguran RT 001/RW 002, Desa Petuguran, Kecamatan Punggelan, Kabupaten Banjarnegara, Provinsi Jawa Tengah
[5038] Geocode: SPPG Banyumas Wangon Klapagading Kulon 2, Jalan Veteran Sunarto, Klapagading Kulon, Wangon, Kab. Banyumas, Jawa Tengah
[5039] Geocode: SPPG Grobogan Grobogan Getasrejo, Jalan Lingkar Utara Purwodadi - Semarang, Kelurahan Getasrejo, Kecamatan Grobogan, Kabupaten Grobogan, Jawa Tengah
[5040] Geocode: SPPG Sragen Sidoharjo Tenggak, Ngagel Rt.18/06, Tenggak, Kec. Sidoharjo, Kab. Sragen, Jawa Tengah, Tenggak, Sidoharjo, Kab. Sragen, Jawa Tengah
[5041] Geocode: SPPG Grobogan Gubug Gubug 2, Dukoh, Gubug, Kecamatan Gubug, Kabupaten Grobogan, Jawa Tengah
[5042] Geocode: SPPG Brebes Tonjong Tonjong, Jl. Raya Tonjong Desa Tonjong, Kecamatan Tonjong, Kabupaten Brebes, Provinsi Jawa Tengah
[5043] Geocode: SPPG Kebumen Kebumen Sumberadi, Desa Sumberadi, Kec. Kebumen, Kab. Kebumen, Jawa Tengah
[5044] Geocode: SPPG Grobogan Ngaringan Ngaringan, Pangkalan, Ngaringan, Kec. Ngaringan, Kabupaten Grobogan, Jawa Tengah
[5045] Geocode: SPPG Grobogan Gubug Jeketro, Jeketro, Kecamatan Gubug Kabupaten Grobogan, Jawa Tengah
[5046] Geocode: SPPG Klaten Jogonalan Pakahan, Rt 11 Rw 06  Tegal Krapyak , Desa Pakahan, Kecamatan Jogonalan, Kabupaten Klaten, Jawa Tengah
[5047] Geocode: SPPG Magelang Pakis Ketundan, Bowongan, Pakis, Area Kebun/Hutan, Ketundan, Kec. Pakis, Kabupaten Magelang, Jawa Tengah 56193, Pakis, Pakis, Kab. Magelang, Jawa Tengah
[5048] Geocode: SPPG Cilacap Maos Karangkemiri, Jl. Raya Maos Desa Karangkemiri Kecamatan Maos Kabupaten Cilacap, Jawa Tengah
[5049] Geocode: SPPG Kota Semarang Gunungpati Mangunsari, JL. JAMBU SARI RT 08 RW 04, KELURAHAN MANGUNSARI, KECAMATAN GUNUNGPATI, KOTA SEMARANG, JAWA TENGAH
[5050] Geocode: SPPG Kota Semarang Gajahmungkur Gajahmungkur, Komplek, Jl. Sultan Agung Jl. Akademi Kepolisian No.131, Candi Baru, Gajahmungkur, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50232
[5051] Geocode: SPPG Magelang Secang Payaman, Malangan 1 Rt 29 Rw 13, Payaman, Secang, Kab. Magelang, Jawa Tengah
[5052] Geocode: SPPG Tegal Balapulang Banjaranyar, Jl. Raya Kaliwungu, Banjar Anyar, Rt 03 / Rw 02, Kecamatan Balapulang, Kabupaten Tegal, Jawa Tengah
[5053] Geocode: SPPG Karanganyar Tawangmangu Kalisoro, Jl. Sekipan, Kramat, Desa Kalisoro, Kecamatan Tawangmangu, Kabupaten Karanganyar 57792, Kalisoro, Tawangmangu, Kab. Karanganyar, Jawa Tengah
[5054] Geocode: SPPG Grobogan Geyer Ledokdawan 2, Ledokdawan, Kecamatan Geyer, Kabupaten Grobogan, Jawa Tengah
[5055] Geocode: SPPG Tegal Margasari Prupuk Selatan, Desa Kesambi, Prupuk Sel., Kec. Margasari, Kabupaten Tegal, Jawa Tengah 52463, Prupuk Selatan, Margasari, Kab. Tegal, Jawa Tengah
[5056] Geocode: SPPG Kota Magelang Magelang Selatan Tidar Selatan, Jl. Soekarno Hatta No.18, Tidar Selatan, Kecamatan Magelang Selatan Kota Magelang, Jawa Tengah
[5057] Geocode: SPPG Semarang Pabelan Pabelan, Jl. Takan Kidul, Pabelan, Kec. Pabelan, Kabupaten Semarang, Jawa Tengah
[5058] Geocode: SPPG Kebumen Adimulyo Candiwulan, Jl. Raya Mangunharjo, Area Sawah, Candi Wulan, Kec. Adimulyo, Kabupaten Kebumen, Jawa Tengah 54363
[5059] Geocode: SPPG Banyumas Karanglewas Pasir Wetan, Jl. Kyai Nur Chakim Dusun I Rt 01 Rw 03, Pasir Wetan, Karanglewas, Kab. Banyumas, Jawa Tengah
[5060] Geocode: SPPG Cilacap Kedungreja Ciklapa, Dusun Purwosari, Desa Ciklapa, RT 002 RW 008, Kecamatan Kedungreja, Kabupaten Cilacap, Provinsi Jawa Tengah
[5061] Geocode: SPPG Jepara Kalinyamatan Banyuputih, Dusun II, Banyuputih, Kec. Kalinyamatan, Kabupaten Jepara, Jawa Tengah 59462.
[5062] Geocode: SPPG Pati Dukuhseti Puncel, Dusun Ngarengan RT003 RW007, Desa Puncel, Kecamatan Dukuhseti, Kabupaten Pati
[5063] Geocode: SPPG Sukoharjo Grogol Gedangan, Jl.Dondong No.36 Dusun 2 ,Kel.Gedangan,Kec.Grogol,Kab.Sukoharjo
[5064] Geocode: SPPG Grobogan Grobogan Grobogan 2, Jl. Slamet riyadi No. 70B, Kelurahan Grobogan, Kecamatan Grobogan, Kabupaten Grobogan, Provinsi Jawa Tengah
[5065] Geocode: SPPG Blora Blora Andongrejo, Jl. Raya Andongrejo, Dukuh Ndenguk, Desa Andongrejo, Kecamatan Blora, Kabupaten Blora, Provinsi Jawa Tengah
[5066] Geocode: SPPG Klaten Karanganom Karanganom, Jl. Raya Karanganom-Penggung, Karanganom, Rt. 001/ Re. 003 ,Ds.Karanganom, Kec. Karanganom, Kab. Klaten, Jawa Tengah
[5067] Geocode: SPPG Pati Winong Winong, RT 001 RW 001, Desa Winong, Kecamatan Winong, Kabupaten Pati , Provinsi Jawa Tengah
[5068] Geocode: SPPG Tegal Bumijawa Dukuhbenda, Jalan Telkom, Desa Gunung Benda, Kecamatan Bumijawa, Kabupaten Tegal, Provinsi Jawa Tengah 52466
[5069] Geocode: SPPG Grobogan Tegowanu Mangunsari, Jalan Raya Purwodadi-Semarang KM.17, Dusun Daplang, Desa. Mangunsari, Kec. Tegowanu, Kab. Grobogan, Jawa Tengah
[5070] Geocode: SPPG Klaten Delanggu Karang, Jalan Tegalrejo RT 021 RW 006, Desa Karang, Kecamatan, Delanggu, Kabupaten Klaten,Jawa Tengah
[5071] Geocode: SPPG Banyumas Cilongok Panembangan, JL. Raya Panembangan - Pernasidi RT 003 RW 003 Desa Panembangan, Kec. Cilongok, Kab. Banyumas
[5072] Geocode: SPPG Purworejo Kemiri Kemirilor, Dusun II RT 01 RW 02, Desa Kemirilor, Kec. Kemiri, Kab. Purworejo provinsi jawa tengah
[5073] Geocode: SPPG Kudus Dawe Margorejo, Desa Margorejo RT 05/RW 05, Kec. Dawe, Kab. Kudus, Jawa Tengah
[5074] Geocode: SPPG Cilacap Nusawungu Banjareja, Desa Banjareja RT 001 RW 004, Kec. Nusawungu, Kab. Cilacap, Jawa Tengah
[5075] Geocode: SPPG Blora Ngawen Ngawen 2, Dukuh Sukolilo, Kelurahan Ngawen, Kecamatan Ngawen, Kabupaten Blora,  Jawa Tengah
[5076] Geocode: SPPG Kebumen Petanahan Karanggadung, Jalan Lingkar Selatan RT 001 / RW 002, Desa Karanggadung, Kecamatan Petanahan, Kabupaten Kebumen, Jawa Tengah
[5077] Geocode: SPPG Wonogiri Wonogiri Wonoboyo, Jalan Melati I No.6, Kelurahan Jatirejo, Kecamatan Wonoboyo, Kabupaten Wonogiri, Jawa Tengah
[5078] Geocode: SPPG Banyumas Kemranjen Alasmalang, JL. Raya Tipar RT.03 RW.04 Ds. Alasmalang Kec. Kemranjen Kab. Banyumas Prov. Jawa Tengah
[5079] Geocode: SPPG Blora Jati Doplang, Dukuh Dukuhan RT 028 RW 004 Ds. Doplang Kecamatan Jati Kab. Blora Jawa Tengah
[5080] Geocode: SPPG Klaten Karangdowo Munggung, Kwageyan RT 18 RW 6 bulusan Karangdowo Klaten
[5081] Geocode: SPPG Kendal Patebon Purwosari 2, Jl Raden Patah Rt 008 Rw 002 Desa Purwosari Kec Patebon
[5082] Geocode: SPPG Grobogan Godong Kemloko, Jl. Raya Gedong Karangrayung No. 92 KM 1
[5083] Geocode: SPPG Cilacap Cilacap Utara Mertasinga, Jl. Rawa Bendungan, Desa Mertasinga, Kecamatan Cilacap Utara, Kabupaten Cilacap
[5084] Geocode: SPPG Kebumen Sempor Selokerto, Jl.Yos Sudarso RT 005/ RW 002, Kel Selokerto, Kec Sempor, Kab Kebumen, Jawa Tengah
[5085] Geocode: SPPG Jepara Nalumsari Karangnongko, Jl.Raya Daren Nalumsari Desa Karangnongko RT 01/01 Kecamatan Nalumsari Kabupaten Jepara
[5086] Geocode: SPPG Temanggung Candiroto Bantir, Dusun Secakran Rt 004 Rw 001, Desa Bantir, Kec. Candiroto, Kab. Temanggung, Jawa Tengah
[5087] Geocode: SPPG Kota Salatiga Argomulyo Tegalrejo, Dusun Delik, Desa Tegalrejo,Kec Argomulyo Kota Salatiga
[5088] Geocode: SPPG Temanggung Kranggan Bengkal, Jalan Secang-Temanggung KM 09, Bengkal, Kecamatan Kranggan, Kabupaten Temanggung, Jawa Tengah
[5089] Geocode: SPPG Purbalingga Mrebet Kradenan, Dusun 3, Tangkisan, Kec. Mrebet Kab. PurbalinggaKradenan, Kec. Mrebet Kab. Purbalingga
[5090] Geocode: SPPG Pati Pucakwangi Tanjungsekar, Desa Tanjungsekar Kecamatan. Pucakwangi Kabupaten. Pati Jawa Tengah
[5091] Geocode: SPPG Blora Bogorejo Sendangrejo, JL JEPON - JATIROGO, DESA SENDANGREJO RT 007 RW 001, KECAMATAN BOGOREJO, KABUPATEN BLORA, PROVINSI JAWA TENGAH
[5092] Geocode: SPPG Kota Surakarta Serengan Danukusuman, Jl. Kapten Pattimura No.25 RT 003 RW 014 Kelurahan Danukusuman Kecamatan Serengan Surakarta Jawa Tengah 57156
[5093] Geocode: SPPG Sukoharjo Polokarto Polokarto, JLN. SUGIHAN-KARANGANYAR, WONOSARI RT.003/RW.013, DESA POLOKARTO, KECAMATAN POLOKARTO, KABUPATEN SUKOHARJO
[5094] Geocode: SPPG Purbalingga Kaligondang Kalikajar, Jl. Raya Trenggiling Kalikajar Kaligondang Purbalingga
[5095] Geocode: SPPG Blora Bogorejo Jeruk, Desa jeruk Rt 02 Rw 01 Kec. Bogorejo Kab. Blora Jawa Tengah
[5096] Geocode: SPPG Grobogan Tawangharjo Pulongrambe, Dusun Mayang, Desa Pulongrambe RT 16 RW 03 Kecamatan Tawangharjo Kabupaten Grobogan
[5097] Geocode: SPPG Boyolali Andong Beji, Jl. Proklamasi No. 20 Ke. beji kec. Andong Kab. Boyolali  Prov. Jawa tengah
[5098] Geocode: SPPG Kebumen Kebumen Bumirejo 1, Jl. MH Sarbini RT 1 RW 4, Bumirejo, Kebumen, Kab. Kebumen
[5099] Geocode: SPPG Klaten Klaten Utara Jonggrangan, Jl. Sersan Sadikin Dk. Jonggrangan Baru RT 03 RW 02 Ds. Jonggrangan Kec. Klaten Utara Kab. Klaten Jawa Tengah
[5100] Geocode: SPPG Cilacap Kesugihan Kalisabuk 1, Jalan Raya Kalisabuk Desa Kalisabuk, Kecamatan Kesugihan, Kabupaten Cilacap
[5101] Geocode: SPPG Kendal Boja Boja, Jalan Pahlawan No.167, Gentan Lor, Kecamatan Boja, Kabupaten Kendal, Jawa tengah
[5102] Geocode: SPPG Banyumas Purwokerto Barat Kober, Jl Kober gg Riswan No 5 01/05 Kel. Kober Kec. Purwokerto Barat Kab. Banyumas
[5103] Geocode: SPPG Brebes Sirampog Kaligiri, Jl. Pakishaji RT 04 RW 04,Desa Kaligiri, Kecamatan Sirampog, Kabupaten Brebes, Provinsi Jawa Tengah
[5104] Geocode: SPPG Kota Semarang Genuk Gebangsari, Jl. Padi Raya, Perumahan Genuk Indah No.231 Kelurahan Gebangsari, Kecamatan Genuk, Kota Semarang, Jawa Tengah
[5105] Geocode: SPPG Temanggung Ngadirejo Ngadirejo 1, Dusun Demangan RT 01 RW 05, Desa Ngadirejo, Kecamatan Ngadirejo, Kabupaten Temanggung, Jawa Tengah
[5106] Geocode: SPPG Brebes Tanjung Sengon, Jl. Cemara gang delima no. 7 RT. 06 RW. 02, Desa Sengon Wetan, Kecamatan Tanjung, Kabupaten Brebes, Kabupaten Brebes
[5107] Geocode: SPPG Banyumas Wangon Banteran, Desa Banteran RT 03 RW 01, Kec, Wangon, Kab. Banyumas
[5108] Geocode: SPPG Blora Kunduran Tawangrejo, Dukuh singgahan, Desa Tawangrejo RT 03 RW 05 kec. kunduran kab. Blora, provinsi Jawa Tengah
[5109] Geocode: SPPG Banyumas Cilongok Gununglurah, Dusun Bojong RT 002 RW 010 Desa Gunung Lurah Kecamatan Cilongok
[5110] Geocode: SPPG Semarang Tuntang Delik, Dsn. Ngesal Rt2 Rw6, Ds. Delik, Kec. Tuntang, Kab. Semarang, Provinsi Jawa Tengah
[5111] Geocode: SPPG Temanggung Kedu Ngadimulyo, Dusun Setrobayan RT 01 RW 02, Desa Ngadimulyo, Kecamatan Kedu, Kabupaten Temanggung,&amp;amp;amp;amp;amp;amp;nbsp;Jawa&amp;amp;amp;amp;amp;amp;nbsp;Tengah
[5112] Geocode: SPPG Temanggung Temanggung Madureso 3, Kavling Sambungsari, Gang 1 No. 2
[5113] Geocode: SPPG Grobogan Wirosari Karangasem, Dusun Sarip RT 006/ RW 004, Kelurahan Karangasem, Kec. Wirosari, Kab. Grobogan
[5114] Geocode: SPPG Magelang Grabag Sidogede, Jl. Kalipucang Desa Sidogede, Kecamatan Grabag, Kabupaten Magelang
[5115] Geocode: SPPG Temanggung Tlogomulyo Tanjungsari, Jl. Tlogomulyo Dusun Karanganom Rt 001/006 Desa Tanjungsari Kecamatan Tlogomulyo Kab Temanggung, Jawa Tengah
[5116] Geocode: SPPG Pekalongan Karangdadap Kaligawe, Jl. Raya Karangdadap, Karanganyar Kidul,Rt.03 Rw.01, Kaligawe, Kec. Karangdadap, Kabupaten Pekalongan, Jawa Tengah
[5117] Geocode: SPPG Banyumas Kemranjen Kecila 2, Jl. Nasional III No.1 Pasewan Rt.06 Rw 02 Kecila Kemranjen Banyumas Jawa Tengah
[5118] Geocode: SPPG Klaten Jogonalan Plawikan,  Desa Plawikan, Kecamatan Jogonalan, Kab. Klaten, Jawa Tengah
[5119] Geocode: SPPG Purworejo Banyuurip Sumbersari, Sumbersari, Banyuurip, Purworejo
[5120] Geocode: SPPG Kebumen Kebumen Adikarso, Jl. Pupus, Adikarso, Kebumen, Kab. Kebumen, Jawa Tengah
[5121] Geocode: SPPG Kota Semarang Tembalang Sendangmulyo 2, Jalan Ketileng Indah Raya No. 3, Kelurahan Sendangmulyo, Kecamatan Tembalang, Kota Semarang, Provinsi Jawa Tengah
[5122] Geocode: SPPG Klaten Trucuk Sajen 2, Desa Sajen, Kecamatan Trucuk, Kabupaten Klaten, Provinsi Jawa Tengah
[5123] Geocode: SPPG Kendal Sukorejo Ngadiwarno, Dusun Kabunan Rt 003 Rw 001, Ngadiwarno, Sukorejo, Kabupaten Kendal, Jawa Tengah
[5124] Geocode: SPPG Rembang Rembang Pasar Banggi, Jalan Raya Kragan-Rembang, Desa Pasarbanggi, Kecamatan Rembang, Kabupaten Rembang, Provinsi Jawa Tengah
[5125] Geocode: SPPG Grobogan Purwodadi Danyang, Jl. Mh. Thamrin Gg IV Sambak, Desa Danyang, Kecamatan Purwodadi, Kabupaten Grobogan, Provinsi Jawa Tengah.
[5126] Geocode: SPPG Boyolali Ampel Tanduk, Jl. Raya Boyolali Semarang Rt. 001 Rw. 001, Tanduk, Ampel, Kab. Boyolali, Jawa Tengah
[5127] Geocode: SPPG Wonosobo Kalikajar Kedalon, Jalan Wonosobo - Purworejo, Desa Kedalon, Kecamatan Kalikajar, Kabupaten Wonosobo, Provinsi Jawa Tengah
[5128] Geocode: SPPG Purbalingga Kejobong Kejobong, Desa Sokanegara, Rt.02 / Rw.04, Kecamatan Kejobong, Kabupaten Purbalingga, Jawa Tengah
[5129] Geocode: SPPG Cilacap Sampang Paberasan, Jl. Dr. Soetomo Paberasan, Paberasan, Kec. Sampang, Kab. Cilacap, Jawa Tengah
[5130] Geocode: SPPG Wonogiri Giritontro Giritontro, Dusun Giritontro Kidul Rt. 004 Rw. 03, Desa Giritontro, Kec. Giritontro, Kab. Wonogiri, Jawa Tengah
[5131] Geocode: SPPG Demak Gajah Gajah, Jl. Raya Demak Kudus Km. 12  Desa Gajah Kecamatan Gajah Kabupaten Demak, Jawa Tengah
[5132] Geocode: SPPG Magelang Mungkid Gondang, Dusun Kramat Gondang Rt 003 Rw 4, Gondang, Kec. Mungkid, Kab. Magelang, Jawa Tengah
[5133] Geocode: SPPG Wonogiri Eromoko Ngadirejo, Plumbon Rt 03 Rw 07 Kec. Eromoko, Ngadirejo, Kab. Wonogiri, Jawa Tengah
[5134] Geocode: SPPG Batang Batang Proyonanggan Selatan, Jl. Ki MangunSarkoro, 03 No.12, Dracik Kembang, Proyonanggan  Selatan, Kec.batang, Kab.Batang, Jawa Tengah
[5135] Geocode: SPPG Kota Magelang Magelang Utara Kedungsari, Jl. Kalimas, Desa Kedungsari, Kec. Magelang Utara, Kota Magelang, Jawa Tengah 56114, Kedungsari, Magelang Utara, Kota Magelang, Jawa Tengah
[5136] Geocode: SPPG Semarang Ungaran Timur Gedanganak, Gedanganak, Kec. Ungaran Timur, Kab Semarang, Jawa Tengah
[5137] Geocode: SPPG Grobogan Brati Karangsari, Dusun Karangsari, Desa Karangsari, Rt 01/01, Kecamatan Brati, Kabupaten Grobogan, Jawa Tengah
[5138] Geocode: SPPG Banjarnegara Kalibening Majatengah, Jl. Raya Kalibening, Desa Majatengah Rt.04/Rw.01, Kecamatan Kalibening, Kabupaten Banjarnegara, Provinsi Jawa Tengah
[5139] Geocode: SPPG Purbalingga Bobotsari Pakuncen, Desa Pekuncen Rt.03/Rw.03, Kecamatan Bobotsari, Kabupaten Purbalingga, Provinsi Jawa Tengah, 53353
[5140] Geocode: SPPG Sukoharjo Tawangsari Tangkisan, Jl. Anggrek Cendrawasih, Rt. 001 Rw. 008, Tangkisan, Kec. Tawangsari, Kab. Sukoharjo, Jawa Tengah
[5141] Geocode: SPPG Cilacap Kroya Bajing 2, Desa Bajing, Kecamatan Kroya, Kabupaten Cilacap, Jawa Tengah
[5142] Geocode: SPPG Temanggung Tembarak Jragan, Rt.02 / Rw.01, Dusun Dukuh, Desa Jragan, Kecamatan Tembarak, Kabupaten Temanggung, Jawa Tengah
[5143] Geocode: SPPG Tegal Bumijawa Gunungagung, Jalan Lapangan Dukuh Lor, Kelurahan Gunungagung, RT.005 RW.001, Kecamatan Bumijawa, Kabupaten Tegal, Provinsi Jawa Tengah
[5144] Geocode: SPPG Jepara Pecangaan Pulodarat, Desa Pulodarat Rt. 14 Rw. 02 Kec. Pecangaan Kab. Jepara, Jawa Tengah
[5145] Geocode: SPPG Kota Surakarta Laweyan Sondakan, Jl Parangkesit No.37, Sondakan, Laweyan, Surakarta 57147, Sondakan, Laweyan, Kota Surakarta, Jawa Tengah
[5146] Geocode: SPPG Karanganyar Karangpandan Dayu, Waru Wetan RT. 01/06, Dayu, Karangpandan, Karanganyar_x000D_
Jawa Tengah (57791) No. Tlp. 0812 2710 8007
[5147] Geocode: SPPG Kota Semarang Semarang Barat Karangayu, Jl. Damarwulan II No.26, Karangayu, Kec. Semarang Barat, Kota Semarang, Jawa Tengah`
[5148] Geocode: SPPG Semarang Tuntang Kesongo 2, Dusun. Ngreco Rt. 001 Rw. 004, Kesongo, Tuntang, Kab. Semarang, Jawa Tengah
[5149] Geocode: SPPG Banjarnegara Bawang Pucang, Jl. Pucang Rt 003 Rw 09 Desa Pucang, Kecamatan Bawang, Kabupaten Banjarnegara, Jawa Tengah
[5150] Geocode: SPPG Banyumas Tambak Purwodadi, Jl. Nasional III Rt 1 Rw 3 , Purwodadi, Tambak, Kab. Banyumas, Jawa Tengah
[5151] Geocode: SPPG Jepara Pecangaan Pecangaan Kulon 2, Pecangaan Kulon Rt 001 Rw 002 Kec. Pecangaan Kab. Jepara Prov. Jawa Tengah, Pecangaan Kulon, Pecangaan, Kab. Jepara, Jawa Tengah
[5152] Geocode: SPPG Pati Kayen Slungkep, Jl. Kayen Slungkep, Slungkep, Kec. Kayen, Kabupaten Pati, Jawa Tengah
[5153] Geocode: SPPG Batang Batang Kauman 2, Jl. Pemuda 103 Rt 03/08, Kelurahan Kauman, Kecamatan Batang, Kabupaten Batang, Jawa Tengah Kode pos 51215
[5154] Geocode: SPPG Semarang Ungaran Timur Kalongan, Jl. Ungaran Mranggen Kelurahan Kalongan Kecamatan Ungaran Timur, Kalongan, Ungaran Timur, Kab. Semarang, Jawa Tengah
[5155] Geocode: SPPG Karanganyar Jumantono Tugu, Dukuh tugu,kelurahan tugu,kec.jumantono,kab.karanganyar jawa tengah
[5156] Geocode: SPPG Demak Guntur Temuroso 3, Jl.Krasak RT.03 RW.04, Desa Temuroso, Kec. Guntur, Kab. Demak
[5157] Geocode: SPPG Grobogan Kradenan Kradenan, Kradenan, Kecamatan Kradenan, Kabupaten Grobogan, Jawa Tengah
[5158] Geocode: SPPG Wonogiri Purwantoro Tegalrejo, Karanglo, Tegalrejo, Purwantoro, Kabupaten Wonogiri, Jawa Tengah
[5159] Geocode: SPPG Wonogiri Jatisrono Jatisrono 2, Dusun Watugede, Jl. Jatisrono Jatipurno RT 009/RW 003, Desa Jatisrono, Kecamatan Jatisrono Kabupaten Wonogiri, Jawa Tengah
[5160] Geocode: SPPG Rembang Rembang Sidowayah, Jl. Dr. Soetomo No.47, Sidowayah Lor, Sidowayah, Kecamatan Rembang, Kabupaten Rembang, Jawa Tengah
[5161] Geocode: SPPG Sragen Tanon Gading, Jl. Gabugan Sumberlawang, Area Sawah, Kelurahan Gading, Kecamatan Tanon, Kabupaten Sragen Jawa Tengah
[5162] Geocode: SPPG Blora Kradenan Medalem, Jl. Randublatung Medalem, Medalem, Kec. Kradenan, Kab. Blora, Jawa Tengah
[5163] Geocode: SPPG Magelang Tegalrejo Purwosari, Dusun Nuren RT. 006 RW. 002 Purwosari, Kec. Tegalrejo, Kab. Magelang, Jawa Tengah
[5164] Geocode: SPPG Semarang Pringapus Pringapus, Ngabean, Pringapus, Kec. Pringapus, Kabupaten Semarang, Jawa Tengah 50214
[5165] Geocode: SPPG Batang Kandeman Ujungnegoro, Jl. Syech Maulana Mahribi Desa/Kelurahan Ujungnegoro Kec.Kademan Kab.Batang 51261, Ujungnegoro, Kandeman, Kab. Batang, Jawa Tengah
[5166] Geocode: SPPG Sukoharjo Bendosari Toriyo, Toriyo, Kec. Bendosari, Kabupaten Sukoharjo, Jawa Tengah
[5167] Geocode: SPPG Banyumas Patikraja Notog, Jl. Raya Notog, Kel. Notog, Kecamatan Patikraja, Kabupaten Banyumas, Jawa Tengah
[5168] Geocode: SPPG Brebes Wanasari Pesantunan, Jl. Pangeran Diponegoro Rt01/Rw01, Pesantunan, Kec. Wanasari, Kab. Brebes, Jawa Tengah
[5169] Geocode: SPPG Pemalang Randudongkal Gembyang, Dusun Dermalang, Desa Gembyang, Kecamatan Randudongkal, Kabupaten Pemalang, Jawa Tengah
[5170] Geocode: SPPG Magelang Salaman Sriwedari, Jl. Magelang Purworejo No.Km 19, Kragilan, Sriwedari, Kec. Salaman, Kabupaten Magelang, Jawa Tengah 56162, Sriwedari, Salaman, Kab. Magelang, Jawa Tengah
[5171] Geocode: SPPG Grobogan Purwodadi Cingkrong, Dusun Cingkrong RT 08 RW 01 Desa Cingkrong, Kecamatan Purwodadi, Kabupaten Grobogan, Jawa Tengah
[5172] Geocode: SPPG Sukoharjo Grogol Telukan 2, Jl. Sadewa, Desa Telukan Kecamatan Grogol Kabupaten Sukoharjo, Jawa Tengah
[5173] Geocode: SPPG Pemalang Taman Asemdoyong, Jl. Lingkar Luar Pantura, Desa Asemdoyong, Kecamatan Taman, Kabupaten Pemalang, Provinsi Jawa Tengah

In [ ]:
df["Latitude"] = latitudes
df["Longitude"] = longitudes

In [ ]:
df.to_excel(OUTPUT_FILE, index=False)
print(f"Selesai! Hasil disimpan ke file: {OUTPUT_FILE}")

Selesai! Hasil disimpan ke file: output_geocode.xlsx

In [ ]:
df_geo = pd.read_excel('output_geocode.xlsx')
df_geo.head()

,NamaSPPG,Alamat,Tanggal Opsnal,Provinsi,wilayah,Nama Kepala,Nama Yayasan,Latitude,Longitude
0,SPPG Aceh Utara Matangkuli Teupin Keubeu,"Jl. Matangkuli Lhoksukon, Teupin Keubeu, Matan...",01-09-2025,ACEH,Wilayah I,Teuku Muhammad Saiful,NaN,NaN,NaN
1,SPPG Aceh Utara Muara Batu Meunasah Drang,"Jalan Medan - Banda Aceh Desa Meunasah Drang, ...",01-09-2025,ACEH,Wilayah I,Muhammad Nur,NaN,5.25274,96.93624
2,SPPG Aceh Barat Samatiga Suak Timah,Jl. Meulaboh Banda Aceh Desa Suak Timah Kab. A...,01-09-2025,ACEH,Wilayah I,M. Hasudungan Situmeang,NaN,NaN,NaN
3,SPPG Aceh Singkil Singkil Utara Gosong Telaga ...,"Praktik Dr. Robinson U. Pasaribu, Jln. Singkil...",01-09-2025,ACEH,Wilayah I,Fadil Muhammad,NaN,2.27774,97.88964
4,SPPG Aceh Selatan Meukek Lhok Aman,Jl. Nasional Tapaktuan Meulaboh Desa Lhok Aman...,01-10-2025,ACEH,Wilayah I,Novri Yanda. S.T.,NaN,NaN,NaN

In [ ]:
df_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NamaSPPG        10000 non-null  object
 1   Alamat          10000 non-null  object
 2   Tanggal Opsnal  10000 non-null  object
 3   Provinsi        10000 non-null  object
 4   wilayah         10000 non-null  object
 5   Nama Kepala     10000 non-null  object
 6   Nama Yayasan    1836 non-null   object
 7   Latitude        7957 non-null   float64
 8   Longitude       7957 non-null   float64
dtypes: float64(2), object(7)
memory usage: 703.3+ KB

In [ ]:
df_null = df_geo[df_geo['Latitude'].isna()]

In [ ]:
df_null.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2043 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   NamaSPPG        2043 non-null   object
 1   Alamat          2043 non-null   object
 2   Tanggal Opsnal  2043 non-null   object
 3   Provinsi        2043 non-null   object
 4   wilayah         2043 non-null   object
 5   Nama Kepala     2043 non-null   object
 6   Nama Yayasan    313 non-null    object
 7   Latitude        0 non-null      float64
 8   Longitude       0 non-null      float64
dtypes: float64(2), object(7)
memory usage: 159.6+ KB

In [ ]:
df_null.to_excel('geo_null.xlsx')

In [ ]:
df_geo.head()

,NamaSPPG,Alamat,Tanggal Opsnal,Provinsi,wilayah,Nama Kepala,Nama Yayasan,Latitude,Longitude
0,SPPG Aceh Utara Matangkuli Teupin Keubeu,"Jl. Matangkuli Lhoksukon, Teupin Keubeu, Matan...",01-09-2025,ACEH,Wilayah I,Teuku Muhammad Saiful,NaN,NaN,NaN
1,SPPG Aceh Utara Muara Batu Meunasah Drang,"Jalan Medan - Banda Aceh Desa Meunasah Drang, ...",01-09-2025,ACEH,Wilayah I,Muhammad Nur,NaN,5.25274,96.93624
2,SPPG Aceh Barat Samatiga Suak Timah,Jl. Meulaboh Banda Aceh Desa Suak Timah Kab. A...,01-09-2025,ACEH,Wilayah I,M. Hasudungan Situmeang,NaN,NaN,NaN
3,SPPG Aceh Singkil Singkil Utara Gosong Telaga ...,"Praktik Dr. Robinson U. Pasaribu, Jln. Singkil...",01-09-2025,ACEH,Wilayah I,Fadil Muhammad,NaN,2.27774,97.88964
4,SPPG Aceh Selatan Meukek Lhok Aman,Jl. Nasional Tapaktuan Meulaboh Desa Lhok Aman...,01-10-2025,ACEH,Wilayah I,Novri Yanda. S.T.,NaN,NaN,NaN

In [ ]:
# df_geo.to_csv('output_geo.csv')

In [ ]:
# import pandas as pd
# df = pd.read_csv('Daftar SPPG_LongLat.csv')
# df.head()

In [ ]:
# df.to_csv('Daftar SPPG_LongLat(2).csv', sep=';', index=False)

In [ ]:
# # import requests

# # API_KEY = "jGE_cqiJdfA-XKRwcsEqPUTctICE2p38XzJj4ooofKQ"

# # BASE_URL = "https://geocode.search.hereapi.com/v1/geocode"

# address = "SPPG Mandailing Natal Siabu Sibaruang Jl. Lintas Sumatra Bukit Tinggi Padang Sidempuan, Desa Sibaruang, Kec. Siabu, Kab. Mandailing Natal, Sumatera Utara"

# params = {
#         "q": address,
#         "apiKey": API_KEY,
#         "in": "countryCode:IDN"
#     }

# response = requests.get(BASE_URL, params=params)
# data = response.json()

# print(data)

# # Cek dulu apakah ada item
# if data.get("items"):
#     first = data["items"][0]
#     position = first.get("position", {})
#     lat = position.get("lat")
#     lng = position.get("lng")

#     print("Alamat:", first.get("title"))
#     print("Latitude:", lat)
#     print("Longitude:", lng)
# else:
#     print("Lokasi tidak ditemukan")

In [ ]:
# import requests
# import pandas as pd
# import time

# API_KEY = ""  # pakai punyamu
# BASE_URL = "https://geocode.search.hereapi.com/v1/geocode"

# # ---- 1. BACA FILE EXCEL (INPUT) ----
# # Misal file bernama 'input_alamat.xlsx' dengan kolom "Alamat"
# INPUT_FILE = "Daftar SPPG.xlsx"
# OUTPUT_FILE = "output_geocode.xlsx"

# # Baca Excel
# df = pd.read_excel(INPUT_FILE)

# # Ambil hanya 1000 baris pertama
# df = df.iloc[:1000].copy()

# # ---- 2. FUNGSI GEOCODE UNTUK 1 ALAMAT ----
# def geocode_address(address: str):
#     if not isinstance(address, str) or not address.strip():
#         return None, None

#     params = {
#         "q": address,
#         "apiKey": API_KEY
#     }

#     try:
#         response = requests.get(BASE_URL, params=params, timeout=10)
#         response.raise_for_status()
#         data = response.json()

#         items = data.get("items", [])
#         if not items:
#             return None, None

#         position = items[0].get("position", {})
#         lat = position.get("lat")
#         lng = position.get("lng")
#         return lat, lng

#     except Exception as e:
#         print(f"Error untuk alamat '{address}': {e}")
#         return None, None

# # ---- 3. LOOP SETIAP BARIS & PANGGIL API ----
# latitudes = []
# longitudes = []

# for idx, row in df.iterrows():
#     alamat = row.get("Alamat", "")
#     print(f"[{idx}] Geocode: {alamat}")

#     lat, lng = geocode_address(alamat)
#     latitudes.append(lat)
#     longitudes.append(lng)

#     # Optional: jeda sedikit untuk jaga-jaga rate limit
#     time.sleep(0.2)

# # Tambahkan kolom hasil ke DataFrame
# df["Latitude"] = latitudes
# df["Longitude"] = longitudes

# # ---- 4. SIMPAN HASIL KE EXCEL ----
# df.to_excel(OUTPUT_FILE, index=False)
# print(f"Selesai! Hasil disimpan ke file: {OUTPUT_FILE}")

In [ ]:
from google.colab import files

files.download(f"Terdownload: {OUTPUT_FILE}")

FileNotFoundError: Cannot find file: Terdownload: output_geocode.xlsx